name: fcm_activity14
description: Activity 14 - Firebase Cloud Messaging in Flutter (CSC 4360)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase core - required before any Firebase service
  firebase_core: ^2.27.1
  # Firebase Cloud Messaging - the main package for this activity
  firebase_messaging: ^14.7.19
  # Local notifications - used to show foreground notifications on Android
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/